### ISSUE TITLE
API Down

### ISSUE THREAD

**Issue by Crilum** [DB-db-dron/weatherDB#6]
**Describe the bug**
I was using the API earlier today, but now it has an `Application Error`.
**To Reproduce**
1. Go to https://weatherdbi.herokuapp.com
```
// // Example code here (if any)
```

**Expected behavior**
For it to work, like it was earlier (aka normally).

**Screenshots**

![image](https://user-images.githubusercontent.com/91354257/170193405-d6390fda-994f-4a0e-bc78-bb38088ec06e.png)

**Additional context**

**Comment by david-sitsky** [comment]
I suspect it is related to the move to a new hosting provider as documented here: https://github.com/DB-db-dron/weatherDB/issues/1.
